name: Build, Push & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push PySpark Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pyspark-image:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pyspark-image:latest

      - name: Build and Push Airflow Webserver Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/airflow-webserver:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/airflow-webserver:latest

      - name: Build and Push Airflow Scheduler Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/airflow-scheduler:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/airflow-scheduler:latest

      - name: Build and Push Airflow Worker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/airflow-worker:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/airflow-worker:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose-dags.yml up -d

      - name: Check Running Containers
        run: docker ps -a
