name: Sync DAG to Docker Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync_dag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify DAG file exists
        run: |
          # Verify that the file exists in the 'dags' directory
          ls -l dags/
          ls -l dags/call_github_repository.py

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Copy DAG to Airflow Docker Container
        run: |
          # Copy DAG file to Airflow containers
          docker cp dags/call_github_repository.py airflow-webserver-container:/opt/airflow/dags/
          docker cp dags/call_github_repository.py airflow-scheduler-container:/opt/airflow/dags/
          docker cp dags/call_github_repository.py airflow-worker-container:/opt/airflow/dags/

      - name: Restart Airflow Containers
        run: |
          # Optionally restart the containers to ensure the new DAGs are picked up
          docker restart airflow-webserver-container
          docker restart airflow-scheduler-container
          docker restart airflow-worker-container
